'use client';
import { useState } from 'react';
import { Card } from '@/components/card';
import { Feedback } from '@/components/feedback';
import { useApi } from '@/lib/hooks/use-api';
import { currencyBRL, numberBR, toInputDate } from '@/lib/utils';
type SummaryResponse = { summary: { despesasPorCategoria: Array<{ categoria: string; total: number }>; despesasPorTipo: Array<{ tipo_despesa: string; total: number }>; usosPorUsuario: Array<{ usuario_uso: string; km_total: number }>; abastecimentos: Array<{ litros_estimados: number; km_total: number; custo_total: number }>; rateio: Array<{ usuario_uso: string; total_responsavel: number }>; }; };
export function ReportsClient() {
  const [inicio, setInicio] = useState(toInputDate(new Date(new Date().getFullYear(), new Date().getMonth(), 1)));
  const [fim, setFim] = useState(toInputDate());
  const { data, loading, error, refresh } = useApi<SummaryResponse>(`/api/reports/summary?start=${inicio}&end=${fim}`);
  return <div className="grid"><Card title="Período do relatório"><div className="form-grid two"><div className="field"><label>Início</label><input type="date" value={inicio} onChange={(e)=>setInicio(e.target.value)} /></div><div className="field"><label>Fim</label><input type="date" value={fim} onChange={(e)=>setFim(e.target.value)} /></div></div><div className="actions" style={{marginTop:12}}><button className="btn primary" onClick={()=>refresh()}>Atualizar</button></div></Card><Feedback error={error} />{loading ? <div className="card">Carregando relatórios...</div> : null}{data ? <div className="grid two"><Card title="Despesas por categoria"><div className="table-wrap"><table><thead><tr><th>Categoria</th><th>Total</th></tr></thead><tbody>{data.summary.despesasPorCategoria.map((item)=><tr key={item.categoria}><td>{item.categoria}</td><td>{currencyBRL(item.total)}</td></tr>)}</tbody></table></div></Card><Card title="Despesas por tipo"><div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Total</th></tr></thead><tbody>{data.summary.despesasPorTipo.map((item)=><tr key={item.tipo_despesa}><td>{item.tipo_despesa}</td><td>{currencyBRL(item.total)}</td></tr>)}</tbody></table></div></Card><Card title="Uso por usuário"><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>KM</th></tr></thead><tbody>{data.summary.usosPorUsuario.map((item)=><tr key={item.usuario_uso}><td>{item.usuario_uso}</td><td>{numberBR(item.km_total,2)} km</td></tr>)}</tbody></table></div></Card><Card title="Abastecimento / consumo estimado"><div className="table-wrap"><table><thead><tr><th>KM total</th><th>Litros estimados</th><th>Custo combustível</th></tr></thead><tbody>{data.summary.abastecimentos.map((item,idx)=><tr key={idx}><td>{numberBR(item.km_total,2)} km</td><td>{numberBR(item.litros_estimados,2)} L</td><td>{currencyBRL(item.custo_total)}</td></tr>)}</tbody></table></div></Card><Card title="Rateio do período"><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Total responsável</th></tr></thead><tbody>{data.summary.rateio.map((item)=><tr key={item.usuario_uso}><td>{item.usuario_uso}</td><td>{currencyBRL(item.total_responsavel)}</td></tr>)}</tbody></table></div></Card></div> : null}</div>;
}
