'use client';
import { useState } from 'react';
import { Card } from '@/components/card';
import { Feedback } from '@/components/feedback';
import { useApi } from '@/lib/hooks/use-api';
import { apiFetch } from '@/lib/api';
import { Vehicle } from '@/lib/types';
import { numberBR } from '@/lib/utils';
export function VehiclesClient() {
  const { data, loading, error, refresh } = useApi<{ vehicles: Vehicle[] }>('/api/vehicles');
  const [success, setSuccess] = useState<string | null>(null);
  const [form, setForm] = useState({ nome:'', placa:'', km_atual:0, km_troca_oleo:5000, ultima_troca_oleo_km:0, consumo_medio_km_litro:10 });
  async function onSubmit(e: React.FormEvent) { e.preventDefault(); setSuccess(null); await apiFetch('/api/vehicles',{method:'POST', body:JSON.stringify(form)}); setSuccess('Veículo salvo com sucesso.'); setForm({ nome:'', placa:'', km_atual:0, km_troca_oleo:5000, ultima_troca_oleo_km:0, consumo_medio_km_litro:10 }); await refresh(); }
  return <div className="grid two"><Card title="Novo veículo"><Feedback error={error} success={success} /><form className="form-grid" onSubmit={onSubmit}><div className="field"><label>Nome</label><input value={form.nome} onChange={(e)=>setForm({...form,nome:e.target.value})} required /></div><div className="field"><label>Placa</label><input value={form.placa} onChange={(e)=>setForm({...form,placa:e.target.value.toUpperCase()})} required /></div><div className="form-grid two"><div className="field"><label>KM atual</label><input type="number" step="0.01" value={form.km_atual} onChange={(e)=>setForm({...form,km_atual:Number(e.target.value)})} required /></div><div className="field"><label>Consumo médio (km/l)</label><input type="number" step="0.01" value={form.consumo_medio_km_litro} onChange={(e)=>setForm({...form,consumo_medio_km_litro:Number(e.target.value)})} required /></div></div><div className="form-grid two"><div className="field"><label>Troca de óleo a cada (km)</label><input type="number" step="0.01" value={form.km_troca_oleo} onChange={(e)=>setForm({...form,km_troca_oleo:Number(e.target.value)})} required /></div><div className="field"><label>Última troca de óleo em (km)</label><input type="number" step="0.01" value={form.ultima_troca_oleo_km} onChange={(e)=>setForm({...form,ultima_troca_oleo_km:Number(e.target.value)})} required /></div></div><div className="actions"><button className="btn primary" type="submit">Salvar veículo</button></div></form></Card><Card title="Veículos cadastrados">{loading ? <p className="empty">Carregando...</p> : null}<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Placa</th><th>KM atual</th><th>Óleo</th></tr></thead><tbody>{data?.vehicles.map((item)=><tr key={item.id}><td>{item.nome}</td><td>{item.placa}</td><td>{numberBR(item.km_atual,2)}</td><td>{numberBR(item.ultima_troca_oleo_km,2)} / {numberBR(item.km_troca_oleo,2)}</td></tr>)}</tbody></table></div>{!data?.vehicles.length ? <p className="empty">Nenhum veículo cadastrado.</p> : null}</Card></div>;
}
